/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "adapter settings": {                            "en": "MoMa settings",                                   "de": "MoMa-Einstellungen",                              "ru": "Настройки MoMa",                                  "pt": "Configurações MoMa",                              "nl": "MoMa-instellingen",                               "fr": "Paramètres MoMa",                                 "it": "Impostazioni MoMa",                               "es": "Configuraciones de MoMa",                         "pl": "Ustawienia MoMa"},
    "interval1": {                                   "en": "Interval 1 (sec)",                                "de": "Intervall 1 (Sek)",                               "ru": "Интервал 1 (сек)",                                "pt": "Intervalo 1 (seg)",                               "nl": "Interval 1 (sec)",                                "fr": " Intervalle 1 (sec)",                             "it": "Intervallo 1 (sec)",                              "es": "Intervalo 1 (seg)",                               "pl": "Interwał 1 (s)"},
    "interval2": {                                   "en": "Interval 2 (min)",                                "de": "Intervall 2 (Min)",                               "ru": "Интервал 2 (мин)",                                "pt": "Intervalo 2 (min)",                               "nl": "Interval 2 (min)",                                "fr": " Intervalle 2 (min)",                             "it": "Intervallo 2 (min)",                              "es": "Intervalo 2 (min)",                               "pl": "Interwał 2 (min)"},
    "interval3": {                                   "en": "Interval 3 (h)",                                  "de": "Intervall 3 (Std)",                               "ru": "Интервал 3 (час)",                                "pt": "Intervalo 3 (horas)",                             "nl": "Interval 3 (uur)",                                "fr": " Intervalle 3 (heures)",                          "it": "Intervallo 3 (ore)",                              "es": "Intervalo 3 (h)",                                 "pl": "Interwał 3 (godz.)"},
    "on save": {                                     "en": "on save adapter restarts with new config immediately", "de": "Beim Speichern von Einstellungen wird der Adapter sofort neu gestartet.", "ru": "При сохранении настроек адаптера он сразу же перезапускается", "pt": "no adaptador de salvar reinicia com nova configuração imediatamente", "nl": "on save-adapter wordt onmiddellijk opnieuw opgestart met nieuwe config", "fr": "sur l'adaptateur de sauvegarde redémarre avec la nouvelle config immédiatement", "it": "su save adapter si riavvia immediatamente con la nuova configurazione", "es": "en el adaptador de guardar se reinicia con nueva configuración de inmediato", "pl": "Zapisanie ustawień natychmiast uruchomi ponownie adapter."},
    "hostname": {                                    "en": "Computername",                                    "de": "Rechnername",                                     "ru": "Имя компьютера",                                  "pt": "Nome do computador",                              "nl": "Computer naam",                                   "fr": "Nom de l'ordinateur",                             "it": "Tiempo de actividad",                             "es": "Nombre de la computadora",                        "pl": "Nazwa komputera"},
    "uptime": {                                      "en": "Uptime",                                          "de": "Uptime",                                          "ru": "Время до начала",                                 "pt": "Tempo de atividade",                              "nl": "Uptime",                                          "fr": "Temps de disponibilité",                          "it": "Uptime",                                          "es": "Tiempo de actividad",                             "pl": "Czas pracy"},
    "load": {                                        "en": "Load",                                            "de": "Auslastung",                                      "ru": "нагрузка",                                        "pt": "Carga",                                           "nl": "Laden",                                           "fr": "Charge",                                          "it": "Carico",                                          "es": "Carga",                                           "pl": "Obciążenie"},
    "temp": {                                        "en": "CPU-Temp.",                                       "de": "CPU-Temp.",                                       "ru": "CPU-темпер.",                                     "pt": "CPU-Temp.",                                       "nl": "CPU-Temp.",                                       "fr": "CPU-Temp.",                                       "it": "CPU-Temp.",                                       "es": "CPU-Temp.",                                       "pl": "Temp. procesora"},
    "updates": {                                     "en": "Updates",                                         "de": "Updates",                                         "ru": "Обновления",                                      "pt": "Atualizações",                                    "nl": "Updates",                                         "fr": "Mises à jour",                                    "it": "Aggiornamenti",                                   "es": "Actualizaciones",                                 "pl": "Aktualizacje"},
};