/*global systemDictionary:true */
"use strict";

systemDictionary = {
	"moma adapter settings": {
		"en": "Adapter settings for moma",
		"de": "Adaptereinstellungen für moma",
		"ru": "Настройки адаптера для moma",
		"pt": "Configurações do adaptador para moma",
		"nl": "Adapterinstellingen voor moma",
		"fr": "Paramètres d'adaptateur pour moma",
		"it": "Impostazioni dell'adattatore per moma",
		"es": "Ajustes del adaptador para moma",
		"pl": "Ustawienia adaptera dla moma",
		"zh-cn": "moma的适配器设置"
	},
    "value": {
		"en": "Value",
		"de": "Wert",
		"ru": "значение",
		"pt": "Valor",
		"nl": "Waarde",
		"fr": "Valeur",
		"it": "Valore",
		"es": "Valor",
		"pl": "Wartość"
	},
    "interval0": {
		"en": "Interval 0 (sec)",
		"de": "Intervall 0 (Sek)",
		"ru": "Интервал 0 (сек)",
		"pt": "Intervalo 0 (seg)",
		"nl": "Interval 0 (sec)",
		"fr": " Intervalle 0 (sec)",
		"it": "Intervallo 0 (sec)",
		"es": "Intervalo 0 (seg)",
		"pl": "Interwał 0 (sekund)"
	},
    "interval1": {
		"en": "Interval 1 (sec)",
		"de": "Intervall 1 (Sek)",
		"ru": "Интервал 1 (сек)",
		"pt": "Intervalo 1 (seg)",
		"nl": "Interval 1 (sec)",
		"fr": " Intervalle 1 (sec)",
		"it": "Intervallo 1 (sec)",
		"es": "Intervalo 1 (seg)",
		"pl": "Interwał 1 (sekund)"
	},
    "interval2": {
		"en": "Interval 2 (min)",
		"de": "Intervall 2 (Min)",
		"ru": "Интервал 2 (мин)",
		"pt": "Intervalo 2 (min)",
		"nl": "Interval 2 (min)",
		"fr": " Intervalle 2 (min)",
		"it": "Intervallo 2 (min)",
		"es": "Intervalo 2 (acta)",
		"pl": "Interwał 2 (minut)"
	},
    "interval3": {
		"en": "Interval 3 (h)",
		"de": "Intervall 3 (Std)",
		"ru": "Интервал 3 (час)",
		"pt": "Intervalo 3 (horas)",
		"nl": "Interval 3 (uur)",
		"fr": " Intervalle 3 (heures)",
		"it": "Intervallo 3 (ore)",
		"es": "Intervalo 3 (horas)",
		"pl": "Interwał 3 (godzin)"
	},
    "interval4": {
		"en": "Interval 4 (days)",
		"de": "Intervall 4 (Tage)",
		"ru": "Интервал 4 (дней)",
		"pt": "Intervalo 4 (dias)",
		"nl": "Interval 4 (dagen)",
		"fr": " Intervalle 4 (jours)",
		"it": "Intervallo 4 (giorni)",
		"es": "Intervalo 4 (días)",
		"pl": "Interwał 4 (dni)"
	},
    "baseboard": {
		"en": "Information about computers motherboard",
		"de": "Informationen zur Hauptplatine des Rechners",
		"ru": "Информация о материнской плате компьютера",
		"pt": "Informações sobre a placa-mãe do computador",
		"nl": "Informatie over het moederbord van de computer",
		"fr": "Informations sur la carte mère de l'ordinateur",
		"it": "Informazioni sulla scheda madre del computer",
		"es": "Información sobre la placa base de la computadora",
		"pl": "Informacje o płycie głównej komputera"
	},
	"chassis": {
		"en": "Information about computers chassis",
		"de": "Informationen zum Gehäuse des Rechners",
		"ru": "Информация о корпусах компьютеров",
		"pt": "Informações sobre chassis de computadores",
		"nl": "Informatie over het chassis van computers",
		"fr": "Informations sur le châssis des ordinateurs",
		"it": "Informazioni sul telaio del computer",
		"es": "Información sobre el chasis de las computadoras",
		"pl": "Informacje o podwoziach komputerów"
	},
    "bios": {
		"en": "Information about computers BIOS",
		"de": "Informationen zum BIOS des Rechners",
		"ru": "Информация о BIOS компьютера",
		"pt": "Informações sobre o BIOS do computador",
		"nl": "Informatie over het BIOS van de computer",
		"fr": "Informations sur le BIOS de l'ordinateur",
		"it": "Informazioni sul BIOS del computer",
		"es": "Información sobre el BIOS de la computadora",
		"pl": "Informacje o BIOSie komputera"
	},
    "system": {
		"en": "Information about computers manufacturer",
		"de": "Informationen zum Hersteller des Rechnersystems",
		"ru": "Информация о производителе компьютерной системы",
		"pt": "Informações sobre o fabricante do sistema de computador",
		"nl": "Informatie over de fabrikant van het computersysteem",
		"fr": "Informations sur le fabricant du système informatique",
		"it": "Informazioni sul produttore del sistema informatico",
		"es": "Información sobre el fabricante del sistema informático",
		"pl": "Informacje o producencie systemu komputerowego"
	},
    "cpu": {
		"en": "Information about computers CPU",
		"de": "Informationen zur CPU des Rechners",
		"ru": "Информация о процессоре компьютера",
		"pt": "Informações sobre a CPU do computador",
		"nl": "Informatie over de CPU van de computer",
		"fr": "Informations sur le processeur de l'ordinateur",
		"it": "Informazioni sulla CPU del computer",
		"es": "Información sobre la CPU del ordenador",
		"pl": "Informacje o procesorze komputera"
	},
    "cpuFlags": {
		"en": "CPU flags available",
		"de": "Leistungsmerkmale der CPU",
		"ru": "Особенности процессора",
		"pt": "Recursos da CPU",
		"nl": "Kenmerken van de CPU ",
		"fr": "Caractéristiques de la CPU",
		"it": "Caratteristiche della CPU",
		"es": "Características de la CPU",
		"pl": "Funkcje procesora"
	},
    "memLayout": {
		"en": "Information about computers memory chips",
		"de": "Informationen zu den verbauten Speicherbausteinen",
		"ru": "Информация о встроенных модулях памяти",
		"pt": "Informações sobre os módulos de memória interna",
		"nl": "Informatie over de ingebouwde geheugenmodules",
		"fr": "Informations sur les modules de mémoire intégrés",
		"it": "Informazioni sui moduli di memoria incorporati",
		"es": "Información sobre los módulos de memoria incorporados",
		"pl": "Informacje o wbudowanych modułach pamięci"
	},
    "diskLayout": {
		"en": "Information about computers harddisks",
		"de": "Informationen zu den verbauten Festplatten",
		"ru": "Информация о установленных жестких дисках",
		"pt": "Informações sobre os discos rígidos instalados",
		"nl": "Informatie over de geïnstalleerde harde schijven",
		"fr": "Informations sur les disques durs installés",
		"it": "Informazioni sui dischi rigidi installati",
		"es": "Información sobre los discos duros instalados",
		"pl": "Informacje o zainstalowanych dyskach twardych"
	},
    "graphics": {
		"en": "Information about computers graphics cards and connected monitors",
		"de": "Verbaute Graphikkarten und angeschlossene Bildschirme",
		"ru": "Встроенные графические карты и подключенные экраны",
		"pt": "Placas gráficas integradas e telas conectadas",
		"nl": "Ingebouwde grafische kaarten en verbonden schermen",
		"fr": "Verbaute Graphikkarten und angeschlossene Bildschirme",
		"it": "Schede grafiche integrate e schermi collegati",
		"es": "Tarjetas gráficas incorporadas y pantallas conectadas",
		"pl": "Wbudowane karty graficzne i połączone ekrany"
	},
    "osInfo": {
		"en": "Information about computers operating system",
		"de": "Informationen zum Betriebssystem",
		"ru": "Информация об операционной системе",
		"pt": "Informações sobre o sistema operacional",
		"nl": "Informatie over het besturingssysteem",
		"fr": "Informations sur le système d'exploitation",
		"it": "Informazioni sul sistema operativo",
		"es": "Información sobre el sistema operativo",
		"pl": "Informacje o systemie operacyjnym"
	},
    "time": {
		"en": "Actual time, timezone and uptime",
		"de": "Aktuelle Zeit, Zeitzone und Uptime",
		"ru": "Текущее время, часовой пояс и время безотказной работы",
		"pt": "Hora atual, fuso horário e tempo de atividade",
		"nl": "Huidige tijd, tijdzone en uptime",
		"fr": "Heure actuelle, fuseau horaire et disponibilité",
		"it": "Ora corrente, fuso orario e tempo di attività",
		"es": "Tiempo actual, zona horaria y tiempo de actividad",
		"pl": "Aktualny czas, strefa czasowa i czas pracy"
	},
    "cpuCurrentSpeed": {
		"en": "Actual cpu and core frequencies",
		"de": "Aktuelle CPU-Taktfrequenzen",
		"ru": "Текущие тактовые частоты процессора",
		"pt": "Freqüências de clock atuais da CPU",
		"nl": "Huidige CPU-klokfrequenties",
		"fr": "Fréquences d'horloge du processeur actuelles",
		"it": "Frequenze attuali dell'orologio della CPU",
		"es": "Frecuencias actuales del reloj de la CPU",
		"pl": "Bieżące częstotliwości zegara procesora"
	},
    "networkConnections": {
		"en": "Actual network connections",
		"de": "Aktuelle Netzwerkverbindungen",
		"ru": "Текущие сетевые подключения",
		"pt": "Conexões de Rede Atuais",
		"nl": "Huidige netwerkverbindingen",
		"fr": "Connexions réseau actuelles",
		"it": "Connessioni di rete attuali",
		"es": "Conexiones de red actuales",
		"pl": "Bieżące połączenia sieciowe"
	},
    "currentLoad": {
		"en": "Actual cpu load",
		"de": "Aktuelle CPU-Last",
		"ru": "Текущая загрузка процессора",
		"pt": "Carga atual da CPU",
		"nl": "Huidige CPU-belasting",
		"fr": "Charge actuelle du processeur",
		"it": "Carico attuale della CPU",
		"es": "Carga actual de la CPU",
		"pl": "Bieżące obciążenie procesora"
	},
    "processes": {
		"en": "Process overview",
		"de": "Übersicht laufende Prozesse",
		"ru": "Обзор запущенных процессов",
		"pt": "Visão geral dos processos em execução",
		"nl": "Overzicht van lopende processen",
		"fr": "Vue d'ensemble des processus en cours",
		"it": "Panoramica dei processi in esecuzione",
		"es": "Resumen de los procesos en ejecución",
		"pl": "Przegląd uruchomionych procesów"
	},
    "mem": {
		"en": "Information about memory usage ",
		"de": "Informationen zur Speicherauslastung",
		"ru": "Информация об использовании памяти",
		"pt": "Informações sobre uso de memória",
		"nl": "Informatie over geheugengebruik",
		"fr": "Informations sur l'utilisation de la mémoire",
		"it": "Informazioni sull'utilizzo della memoria",
		"es": "Información sobre el uso de la memoria",
		"pl": "Informacje o użyciu pamięci"
	},
    "battery": {
		"en": "State of charge and information about battery",
		"de": "Ladezustand und Informationen zur Batterie",
		"ru": "Состояние заряда и информации об аккумуляторах",
		"pt": "Estado de carga e informação da bateria",
		"nl": "Toestand van lading en batterij-informatie",
		"fr": "Etat de charge et informations sur la batterie",
		"it": "Stato di carica e informazioni sulla batteria",
		"es": "Estado de carga e información de la batería",
		"pl": "Stan naładowania i informacje o akumulatorze"
	},
    "cpuTemperature": {
		"en": "Temperatures of cpu and cores",
		"de": "CPU- und Kern-Temperaturen",
		"ru": "Температура процессора и ядра",
		"pt": "Temperaturas do CPU e núcleo",
		"nl": "CPU en kerntemperaturen",
		"fr": "Températures de CPU et base",
		"it": "Temperature del CPU e core",
		"es": "Temperaturas CPU y centrales",
		"pl": "Temperatura procesora i rdzenia"
	},
    "networkStats": {
		"en": "Network statistics",
		"de": "Netzwerkstatistiken",
		"ru": "Сетевая статистика",
		"pt": "Estatísticas de rede",
		"nl": "Network statistieken",
		"fr": "Les statistiques du réseau",
		"it": "statistiche di rete",
		"es": "Estadísticas de la red",
		"pl": "Statystyki sieci"
	},
    "fullLoad": {
		"en": "Average load since last boot",
		"de": "Durchschnittliche Last seit letztem Start",
		"ru": "Средняя загрузка с момента последнего запуска",
		"pt": "Carga média desde o último início",
		"nl": "Gemiddelde belasting sinds de laatste start",
		"fr": "Charge moyenne depuis le dernier démarrage",
		"it": "Carico medio dall'ultimo avvio",
		"es": "Carga media desde el último inicio",
		"pl": "Średnie obciążenie od ostatniego uruchomienia"
	},
    "users": {
		"en": "Current user sessions",
		"de": "Angemeldete User-Sessions",
		"ru": "Зарегистрированные пользовательские сеансы",
		"pt": "Sessões de usuários registrados",
		"nl": "Geregistreerde gebruikerssessies",
		"fr": "Sessions utilisateur enregistrées",
		"it": "Sedi utente registrate",
		"es": "Sesiones de usuarios registrados",
		"pl": "Zarejestrowane sesje użytkownika"
	},
    "fsSize": {
		"en": "Information about computers file system",
		"de": "Informationen zum Dateisystem",
		"ru": "Информация о файловой системе",
		"pt": "Informações sobre o sistema de arquivos",
		"nl": "Informatie over het bestandssysteem",
		"fr": "Informations sur le système de fichiers",
		"it": "Informazioni sul file system",
		"es": "Información sobre el sistema de archivos",
		"pl": "Informacje o systemie plików"
	},
    "blockDevices": {
		"en": "Connected block devices",
		"de": "Angeschlossene Datenträger",
		"ru": "Подключенные диски",
		"pt": "Discos conectados",
		"nl": "Verbonden schijven",
		"fr": "Disques connectés",
		"it": "Dischi collegati",
		"es": "Discos conectados",
		"pl": "Połączone dyski"
	},
    "fsStats": {
		"en": "File access statistics",
		"de": "Datei-Zugriffs-Statistiken",
		"ru": "Доступ к файлам Статистика",
		"pt": "Arquivo Estatísticas de Acesso",
		"nl": "File Access Statistics",
		"fr": "Statistiques d'accès aux fichiers",
		"it": "File delle statistiche di accesso",
		"es": "Presentar Estadísticas de Acceso",
		"pl": "File Access Statystyka"
	},
    "disksIO": {
		"en": "IO statistics of block devices",
		"de": "IO-Statistik zu den Datenspeichern",
		"ru": "Статистика ввода-вывода для памяти данных",
		"pt": "Estatísticas de IO para as memórias de dados",
		"nl": "IO-statistieken voor de datageheugens",
		"fr": "Statistiques IO pour les mémoires de données",
		"it": "Statistiche IO per le memorie di dati",
		"es": "Estadísticas IO para las memorias de datos",
		"pl": "Statystyki IO dla pamięci danych"
	},
    "networkInterfaceDefault": {
		"en": "Default network interface",
		"de": "Standard-Netzwerkschnittstelle",
		"ru": "Стандартный сетевой интерфейс",
		"pt": "Interface de rede padrão",
		"nl": "Standaard netwerkinterface",
		"fr": "Interface réseau par défaut",
		"it": "Interfaccia di rete standard",
		"es": "Interfaz de red estándar",
		"pl": "Standardowy interfejs sieciowy"
	},
	"networkInterfaces": {
		"en": "Available network interfaces",
		"de": "Verfügbare Netzwerkschnittstellen",
		"ru": "Доступные сетевые интерфейсы",
		"pt": "Interfaces de rede disponíveis",
		"nl": "Beschikbare netwerkinterfaces",
		"fr": "Interfaces réseau disponibles",
		"it": "Interfacce di rete disponibili",
		"es": "Interfaces de red disponibles",
		"pl": "Dostępne interfejsy sieciowe"
	},
    "updates": {
		"en": "Check for available updates",
		"de": "Auf verfügbare Updates prüfen",
		"ru": "Проверить наличие обновлений",
		"pt": "Verificar atualizações disponíveis",
		"nl": "Controleer op beschikbare updates",
		"fr": "Vérifier les mises à jour disponibles",
		"it": "Controlla gli aggiornamenti disponibili",
		"es": "Compruebe las actualizaciones disponibles",
		"pl": "Sprawdź dostępne aktualizacje"
	},
	"uuid": {
		"en": "UUID's of installation",
		"de": "UUIDs der Systeminstallation",
		"ru": "UUID's установки",
		"pt": "UUID da instalação",
		"nl": "UUID's van installatie",
		"fr": "UUID de l'installation",
		"it": "UUID di installazione",
		"es": "UUID's de instalación",
		"pl": "Identyfikatory UUID instalacji"
	},
	"shell": {
		"en": "Default system shell",
		"de": "Standard-Systemshell",
		"ru": "Системная оболочка по умолчанию",
		"pt": "Shell do sistema padrão",
		"nl": "Standaard systeemshell",
		"fr": "Shell système par défaut",
		"it": "Shell di sistema predefinita",
		"es": "Shell del sistema predeterminado",
		"pl": "Domyślna powłoka systemu"
	},
	"versions": {
		"en": "Versions of installed software packages",
		"de": "Versionen der installierten Softwarepakete",
		"ru": "Версии установленных пакетов программного обеспечения",
		"pt": "Versões de pacotes de software instalados",
		"nl": "Versies van geïnstalleerde softwarepakketten",
		"fr": "Versions des packages logiciels installés",
		"it": "Versioni di pacchetti software installati",
		"es": "Versiones de paquetes de software instalados",
		"pl": "Wersje zainstalowanych pakietów oprogramowania"
	},
	"sudo info": {
		"en": "Linux - Insert following into /etc/sudoers: iobroker	ALL = NOPASSWD: ALL",
		"de": "Linux - Folgendes einfügen in /etc/sudoers: iobroker	ALL = NOPASSWD: ALL",
		"ru": "Linux - Вставить следующее в /etc/sudoers: iobroker	ALL = NOPASSWD: ALL",
		"pt": "Linux - Insira o seguinte em /etc/sudoers: iobroker	ALL = NOPASSWD: ALL",
		"nl": "Linux - Volgende invoegen in /etc/sudoers: iobroker	ALL = NOPASSWD: ALL",
		"fr": "Linux - Insérer ce qui suit dans /etc/sudoers: iobroker	ALL = NOPASSWD: ALL",
		"it": "Linux - Inserisci in seguito /etc/sudoers: iobroker	ALL = NOPASSWD: ALL",
		"es": "Linux - Insertar siguiendo en /etc/sudoers: iobroker	ALL = NOPASSWD: ALL",
		"pl": "Linux - Wstaw następujące po /etc/sudoers: iobroker	ALL = NOPASSWD: ALL"
	},
    "on save": {
		"en": "On save adapter restarts with new config immediately",
		"de": "Beim Speichern von Einstellungen wird der Adapter sofort neu gestartet.",
		"ru": "При сохранении настроек адаптера он сразу же перезапускается",
		"pt": "No adaptador de salvar reinicia com nova configuração imediatamente",
		"nl": "Bij het opslaan adapter wordt onmiddellijk opnieuw opgestart met nieuwe config",
		"fr": "Sur l'adaptateur de sauvegarde redémarre avec la nouvelle config immédiatement",
		"it": "Su save adapter si riavvia immediatamente con la nuova configurazione",
		"es": "En el adaptador de guardar se reinicia con nueva configuración de inmediato",
		"pl": "Zapisanie ustawień natychmiast uruchomi ponownie adapter."
	},
};